### PR TITLE
Adding support for counter64

### LINKED ISSUE #24: Counter64 OID Values Are Returned as nil
This is a follow up to #23. Apologies for not being clear previously.

For reference, here is my setup.

Ruby:
```
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
```

Ubuntu:
```
$ cat /etc/issue
Ubuntu 16.04.4 LTS \n \l
```

ruby-netsnmp Gem:
```
$ gem query netsnmp

*** LOCAL GEMS ***

netsnmp (0.1.5)
```

The values of Counter64 OIDs are reported as nil. Compare the following.

Here is an example of `ifHCInOctets` table returned by snmpwalk:
```
$ snmpwalk -v3 -l authNoPriv -u myuser -a sha -A "mypassword" myhost.example.com ifHCInOctets
IF-MIB::ifHCInOctets.1 = Counter64: 92491218
IF-MIB::ifHCInOctets.2 = Counter64: 16155773819
IF-MIB::ifHCInOctets.3 = Counter64: 0
IF-MIB::ifHCInOctets.15 = Counter64: 14546980809
IF-MIB::ifHCInOctets.17 = Counter64: 15662965
IF-MIB::ifHCInOctets.18 = Counter64: 11646536
IF-MIB::ifHCInOctets.19 = Counter64: 12299679
IF-MIB::ifHCInOctets.20 = Counter64: 122748726
IF-MIB::ifHCInOctets.21 = Counter64: 12830296
```

And here is the same table values returned by Sensu plugin using ruby-netsnmp gem:
```
$ ruby metrics-snmp-if.rb -h myhost.example.com -u myuser -p mypassword -l auth_no_priv | grep ifHCInOctets
snmp.interfaces.lo.ifHCInOctets
snmp.interfaces.eth0.ifHCInOctets
snmp.interfaces.vti90.ifHCInOctets
snmp.interfaces.vti91.ifHCInOctets
snmp.interfaces.vti0.ifHCInOctets
snmp.interfaces.vti1.ifHCInOctets
snmp.interfaces.vti2.ifHCInOctets
snmp.interfaces.vti3.ifHCInOctets
```

I believe the simple fix is to modify `convert_application_asn` method in lib/netsnmp/varbind.rb from:
```
    def convert_application_asn(asn)
      case asn.tag
      when 0 # IP Address
        IPAddr.new_ntoh(asn.value)
      when 1, # ASN counter 32
           2 # gauge
        val = asn.value
        val.prepend("\x00") while val.bytesize < 4
        asn.value.unpack("N*")[0] || 0
```
to:
```
    def convert_application_asn(asn)
      case asn.tag
      when 0 # IP Address
        IPAddr.new_ntoh(asn.value)
      when 1, # ASN counter 32
           2, # gauge
           6  # ASN Counter 64
        val = asn.value
        val.prepend("\x00") while val.bytesize < 4
        asn.value.unpack("N*")[0] || 0
```

Example of my output after the fix is applied:
```
$ ruby metrics-snmp-if.rb -h myhost.example.com -u myuser -p mypassword -l auth_no_priv | grep ifHCInOctets
snmp.interfaces.lo.ifHCInOctets 92491218 1530802973
snmp.interfaces.eth0.ifHCInOctets 63110204 1530802973
snmp.interfaces.vti90.ifHCInOctets 56824152 1530802973
snmp.interfaces.vti91.ifHCInOctets 15665023 1530802973
snmp.interfaces.vti0.ifHCInOctets 11648594 1530802973
snmp.interfaces.vti1.ifHCInOctets 12301529 1530802973
snmp.interfaces.vti2.ifHCInOctets 122750576 1530802973
snmp.interfaces.vti3.ifHCInOctets 12832458 1530802973
```

### PR DESCRIPTION
**Pull request by HoneyryderChuck**
Fixes #24  and #23 . 

@ichekaldin would this be ok?

### CODE REVIEW

**Comment by ichekaldin** [comment]
@HoneyryderChuck this is definitely so much better than anything I was trying to put together.

I ran this against my test router. Here is the output from `snmpwalk` (which presumably knows what it's doing):

```
$ snmpwalk -v3 -l authNoPriv -u myuser -a sha -A mypassword myhost.example.com 1.3.6.1.2.1.31.1.1.1 | grep HCOutOctets
...
IF-MIB::ifHCOutOctets.26 = Counter64: 308481190
IF-MIB::ifHCOutOctets.27 = Counter64: 308344456
IF-MIB::ifHCOutOctets.32 = Counter64: 63329710
IF-MIB::ifHCOutOctets.33 = Counter64: 2812593284
IF-MIB::ifHCOutOctets.34 = Counter64: 150599036658
IF-MIB::ifHCOutOctets.35 = Counter64: 2613579146118
```

Output from my plugin that users the gem:

```
$ ruby metrics-snmp-if.rb -h myhost.example.com -u myuser -p mypassword -l auth_no_priv | grep ifHCInOctets
snmp.interfaces.26.ifHCOutOctets 308481190 1553613623
snmp.interfaces.27.ifHCOutOctets 308344456 1553613623
snmp.interfaces.32.ifHCOutOctets 63329710 1553613623
snmp.interfaces.33.ifHCOutOctets 7107560579 1553613623
snmp.interfaces.34.ifHCOutOctets 4570148628 1553613623
snmp.interfaces.35.ifHCOutOctets 6533998053 1553613623
```

It looks like this works well when the value is within Counter32 range (0 to 4294967295) - interfaces 26, 27, and 32 in my example.

On the other hand, the values outside Counter32 range do not match - interfaces 33, 34, and 35 in my example.

**Comment by HoneyryderChuck** [comment]
I see. So I'm definitely off in my asn representation of a counter64. Would you mind getting me a more verbose output for one of the examples that failed? Use snmpget and the direct oid, and then run it with verbosity on.

**Comment by ichekaldin** [comment]
Here is a snmpget response for one of the "good" interfaces:

```
[root@fgprd-em7-collector-cse1-app001 ~]# snmpget -v3 -l authNoPriv -u myuser -a sha -A mypassword myhost.example.com 'IF-MIB::ifHCOutOctets.26' -Ddump
...
dumpv_recv:     Command RESPONSE
dumph_recv:         request_id
dumpx_recv:          02 04 2E 22 08 AA
dumpv_recv:            Integer: 773982378 (0x2E2208AA)
dumph_recv:         error status
dumpx_recv:          02 01 00
dumpv_recv:            Integer: 0 (0x00)
dumph_recv:         error index
dumpx_recv:          02 01 00
dumpv_recv:            Integer: 0 (0x00)
dumph_recv:         VarBindList
dumph_recv:           VarBind
dumph_recv:             Name
dumpx_recv:              06 0B 2B 06 01 02 01 1F 01 01 01 0A 1A
dumpv_recv:                ObjID: IF-MIB::ifHCOutOctets.26
dumph_recv:             Value
dumpx_recv:              46 04
dumpv_recv:              Counter64: 309084502
IF-MIB::ifHCOutOctets.26 = Counter64: 309084502
```

And here is a response for an interface that didn't work:

```
[root@fgprd-em7-collector-cse1-app001 ~]# snmpget -v3 -l authNoPriv -u myuser -a sha -A mypassword myhost.example.com 'IF-MIB::ifHCOutOctets.26' -Ddump
...
dumpv_recv:     Command RESPONSE
dumph_recv:         request_id
dumpx_recv:          02 04 06 A2 C1 8F
dumpv_recv:            Integer: 111329679 (0x6A2C18F)
dumph_recv:         error status
dumpx_recv:          02 01 00
dumpv_recv:            Integer: 0 (0x00)
dumph_recv:         error index
dumpx_recv:          02 01 00
dumpv_recv:            Integer: 0 (0x00)
dumph_recv:         VarBindList
dumph_recv:           VarBind
dumph_recv:             Name
dumpx_recv:              06 0B 2B 06 01 02 01 1F 01 01 01 0A 23
dumpv_recv:                ObjID: IF-MIB::ifHCOutOctets.35
dumph_recv:             Value
dumpx_recv:              46 06
dumpv_recv:              Counter64: 2613579752238
IF-MIB::ifHCOutOctets.35 = Counter64: 2613579752238
```

In both cases I omitted the authentication portion of the output. Does this help?

**Comment by HoneyryderChuck** [comment]
@ichekaldin could you try again?

**Comment by ichekaldin** [comment]
@HoneyryderChuck I think you nailed it.

Here is the output from `snmpwalk`:

```
$ snmpwalk -v3 -l authNoPriv -u myuser -a sha -A mypassword myhost.example.com 1.3.6.1.2.1.31.1.1.1 | grep HCOutOctets
...
IF-MIB::ifHCOutOctets.26 = Counter64: 326126376
IF-MIB::ifHCOutOctets.27 = Counter64: 325969134
IF-MIB::ifHCOutOctets.32 = Counter64: 80973892
IF-MIB::ifHCOutOctets.33 = Counter64: 2830233676
IF-MIB::ifHCOutOctets.34 = Counter64: 150616657342
IF-MIB::ifHCOutOctets.35 = Counter64: 2613596760612
```

And here is the output from the plugin:

```
$ ruby metrics-snmp-if.rb -h myhost.example.com -u myuser -p mypassword -l auth_no_priv | grep ifHCInOctets
...
snmp.interfaces.26.ifHCOutOctets 326126242 1554235819
snmp.interfaces.27.ifHCOutOctets 325969000 1554235819
snmp.interfaces.32.ifHCOutOctets 80973892 1554235819
snmp.interfaces.33.ifHCOutOctets 2830233676 1554235819
snmp.interfaces.34.ifHCOutOctets 150616657342 1554235819
snmp.interfaces.35.ifHCOutOctets 2613596760612 1554235819
```

As far as I can tell, they match.

**Comment by HoneyryderChuck** [comment]
Perfect! Tomorrow I'll cook a release, once I fix these CI pipeline issues...

**Pull request merged**
