### PR TITLE
Aes encryption tests

### PR DESCRIPTION
**Pull request by tfluehmann**
added test for checking correctness of aes encryption/decryption and ASN1 transfer

### CODE REVIEW

**Comment by HoneyryderChuck** [comment]
Are these tests part of some specification, or are these just testing a particular use case of yours?

In the second case, I'd prefer not to merge them, as they'd be testing the AES and ASN1 modules from openssl, and that's an external already-tested dependency (correctness has to be ensured there). Encryption modules are already "tested" when ran in the integration tests.

**Comment by HoneyryderChuck** [comment]
I meant, [this test block](https://github.com/swisscom/ruby-netsnmp/blob/master/spec/client_spec.rb#L165-L183) already tests this AES implementation.

**Comment by tfluehmann** [comment]
@HoneyryderChuck Ok, sorry my bad, haven't checked that part.

**Comment by HoneyryderChuck** [comment]
No worries. Just to recap, I'm OK if the unit tests cover edge cases, I just thought that this wasn't the case here.

Thx anyway for the contribution!

**Pull request closed without merging**
