### PR TITLE
Allow get() to retrieve multiple oids with one request

### PR DESCRIPTION
**Pull request by Sebbb**
Probably a dirty hack, but "works for me". Maybe useful for others as well.

### CODE REVIEW

**Comment by HoneyryderChuck** [comment]
@Sebbb ,

Looks good. I'd prefer to keep one method and support multiple oids in the signature, but that'd break compatibility, so your patch is alright. Only thing missing is a test. 

I'd suggest [looking at this for reference](https://github.com/swisscom/ruby-netsnmp/blob/master/spec/support/request_examples.rb#L12-L17) (for simplicity sake, I'd also suggest using [these oids](https://github.com/swisscom/ruby-netsnmp/blob/master/spec/client_spec.rb#L16-L17). 

Here is the [reference on how to run tests locally](https://github.com/swisscom/ruby-netsnmp#tests) (you will need docker). I don't have a more exhaustive guide for it, but feel free to ping with questions, that might be useful later when creating one.

**Comment by tzhbami7** [comment]
ping

**Comment by HoneyryderChuck** [comment]
> Only thing missing is a test.

@tzhbami7 do you want to finish what @Sebbb started?

**Comment by tzhbami7** [comment]
I will when I find time for it ;)

**Comment by HoneyryderChuck** [comment]
Fixed with https://github.com/swisscom/ruby-netsnmp/commit/9032f8b32437df1ba21bbf30aeb9589371bf4ce7

**Pull request closed without merging**
