### PR TITLE
[29] Add SHA-256 to auth_protocols

### LINKED ISSUE #29: HMAC-SHA-2 Authentication Protocols in the User-based Security Model (USM) for SNMPv3
How you plan the support of SHA-2 for SNMPv3 ?

https://tools.ietf.org/html/rfc7630

### PR DESCRIPTION
**Pull request by jinxka**
Implementing https://datatracker.ietf.org/doc/html/rfc7860

Resolve #29

### CODE REVIEW

**Comment by HoneyryderChuck** [comment]
@jinxka thanks for working on this!

I added a commit where I update the snmp simulator and added the auth sha256 user you require. Tests are still failing, so I guess you still have work to do. I'll start reviewing this once the build is green.

For reference, [here's how you can run the test suite using docker](https://github.com/swisscom/ruby-netsnmp#tests), which will already bundle the snmp simulator instance.

**Comment by jinxka** [comment]
Hello @HoneyryderChuck , I think there is an issue with the image honeyryderchuck/snmp-server-emulator used by the CI.

It looks like this image is using snmpsim 0.3.0, but the support for SHA2 needs version 0.4.1 or later (https://github.com/etingof/snmpsim/releases/tag/v0.4.1).

Could you update the image to use the latest version of https://github.com/etingof/snmpsim ?

Below is the error I got in the container logs after adding  `--v3-auth-proto=SHA256` to the docker-compose.yml

```
❯ docker container logs 5b5d328c69b1
Scanning "/home/snmp_server/.snmpsim/variation" directory for variation modules...
Directory "/home/snmp_server/.snmpsim/variation" does not exist
Scanning "/usr/local/snmpsim/variation" directory for variation modules...
Directory "/usr/local/snmpsim/variation" does not exist
Scanning "/usr/local/share/snmpsim/variation" directory for variation modules...
Directory "/usr/local/share/snmpsim/variation" does not exist
Scanning "/usr/local/lib/python2.7/site-packages/snmpsim-0.3.0-py2.7.egg/snmpsim/variation" directory for variation modules...
A total of 9 modules found in /usr/local/lib/python2.7/site-packages/snmpsim-0.3.0-py2.7.egg/snmpsim/variation
Cache directory "/tmp/snmpsim" created
Initializing variation modules...
Variation module "notification" loaded OK
Variation module "sql" load FAILED: database type not specified
Variation module "redis" load FAILED: Redis connect parameters not specified
Variation module "numeric" loaded OK
Variation module "subprocess" loaded OK
Variation module "delay" loaded OK
Variation module "multiplex" loaded OK
Variation module "error" loaded OK
Variation module "writecache" loaded OK
ERROR: bad v3 auth protocol SHA256
```

**Comment by HoneyryderChuck** [comment]
@jinxka I just wrote in the last message that I updated it, but your force-push removed my commit :( 

I've since merged it into master, so feel free to rebase your branch.

**Comment by jinxka** [comment]
> @jinxka I just wrote in the last message that I updated it, but your force-push removed my commit :(

 I'm deeply sorry for that, I'm not used to have others adding commits to my PR.

**Comment by HoneyryderChuck** [comment]
No worries, everything can be fixed :)

I'll see if I can review the PR at some point today. Again, thanks for working on this, was probably long overdue.

**Comment by HoneyryderChuck** [comment]
@jinxka I think it's good as it is. I'll do some small tweaks before releasing, but overall LGTM. 👍 

Again, thank you.

**Pull request merged**
