### PR TITLE
[bug] #13 - Timeout::Error does not exists

### LINKED ISSUE #13: `Timeout::Error` does not exists

### PR DESCRIPTION
**Pull request by NetForces**
closes #13

### CODE REVIEW

**Comment by HoneyryderChuck** [comment]
Thx for the PR. Unfortunately this is not the fix.

You should add :

require "timeout"

At the beginning of the file.

Could you open a new PR?

**Comment by NetForces** [comment]
Changed the fix. Works as expected on my test rig.

**Comment by HoneyryderChuck** [comment]
Can you do something about the ci errors? Rubocop is complaining ;)

**Comment by NetForces** [comment]
Will try to adress it this afternoon.

**Comment by HoneyryderChuck** [comment]
@NetForces any progress? For the record this should be fairly straightforward, just do `rubocop -a` and commit the changes.

**Comment by NetForces** [comment]
@HoneyryderChuck all yours. Sorry for the delay.

**Comment by HoneyryderChuck** [comment]
thx again! will see about not delaying the release much further.

**Comment by HoneyryderChuck** [comment]
0.1.4 is out

**Pull request merged**
